### ISSUE TITLE
We can't move `BSC_FILTER_LOGS_FROM_BLOCK` because we need all events for fee api

### ISSUE THREAD

**Issue by nacknime-official** [ambrosus/ambrosus-bridge#341]
In the current version of fee api we can move the var, losing the old events but "proportionally".

But in #317 we can't move it because there the relay grabs the prices from explorers, but the count of withdrawals - still from events.

**Comment by SvineruS** [comment]
We can get withdraws count from submitTransfersXXX transactions call data, but it's need to parse different variants of this method for this.
This is also a bad option if we implement PIDR, because we will still need to receive all Withdraw events to find out the transferFee

**Comment by nacknime-official** [comment]
With #355 we can move that var.
